# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - PoolSensorAPI

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs:
  - job: 'Build'
    displayName: 'Build job'

    variables:
      workingDirectory: '$(System.DefaultWorkingDirectory)/PoolSensorAPI'

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore dependencies'
      inputs:
        command: 'restore'
        feedsToUse: 'select'
        vstsFeed: 'PoolSensor/PoolSensor-Models'
        projects: '$(workingDirectory)/*.csproj'
        
    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: build
        arguments: '-c $(buildConfiguration)'
        projects: '$(workingDirectory)/*.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: "Run unit tests"
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--no-build -c $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: 'Publish and zip the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        arguments: '--no-build -c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        projects: '$(workingDirectory)/*.csproj'
        zipAfterPublish: true
    
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: 'Deploy'
  displayName: 'Deploy to dev environment'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            inputs: 
              azureSubscription: 'Azure subscription mattias(909eb5e0-25b8-4ea2-a491-e39f55abbcb4)'
              appType: 'webApp'
              appName: 'PoolSensorAPI'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'